#!/usr/bin/env bash
set -e
set -u
image_name=ome_zarr_suite_bf2raw
git clone git://github.com/glencoesoftware/bioformats2raw 1>&2
cd bioformats2raw
docker build -t ${image_name} . 1>&2
cd ..
docker run --rm -v $PWD:/out ${image_name} a.fake /out/zarr "$@" 1>&2
# Only print return value to stdout
echo ${PWD}/zarr/data.zarr
