#!/usr/bin/env bash
set -e
set -u
image_name=ome-zarr-suite-bf2raw
test -e $image_name || git clone https://github.com/glencoesoftware/bioformats2raw $image_name 1>&2
cd $image_name
docker build -t ${image_name} . 1>&2
cd ..
echo $PWD 1>&2
docker run --rm -u $(id -u) -v $PWD:/out ${image_name} a.fake /out/bf2raw "$@" 1>&2
# Only print return value to stdout
echo ${PWD}/bf2raw/0
