#!/usr/bin/env bash
set -e
set -u
image_name=ome_zarr_suite_bf2raw
SUITE=ome-zarr-bf2raw-suite
test -e $SUITE || git clone git://github.com/glencoesoftware/bioformats2raw $SUITE 1>&2
cd $SUITE
docker build -t ${image_name} . 1>&2
cd ..
echo $PWD 1>&2
docker run --rm -u $(id -u) -v $PWD:/out ${image_name} a.fake /out/bf2raw "$@" 1>&2
# Only print return value to stdout
echo ${PWD}/bf2raw/0
