#!/usr/bin/env bash
set -e
set -u

SUITE=omero-ms-zarr-suite
test -e $SUITE || git clone git://github.com/ome/omero-ms-zarr $SUITE 1>&2

cd $SUITE
docker-compose up -d

function finish {
    echo "Cleaning up"
    docker-compose down -v
}
trap finish EXIT

# from: omero-server-docker/test.sh
OMERO=/opt/omero/server/venv3/bin/omero
SERVER="localhost:4064"

# Wait up to 2 mins
i=0
while ! docker-compose exec -T omeroserver $OMERO login -C -s root@$SERVER -w omero; do
    i=$(($i+1))
    if [ $i -ge 24 ]; then
        echo "$(date) - OMERO.server still not reachable, giving up"
        exit 1
    fi
    echo "$(date) - waiting for OMERO.server..."
    sleep 5
done

docker-compose exec -T omeroserver touch /tmp/a.fake 1>&2
docker-compose exec -T omeroserver env OMERODIR=/opt/omero/server/OMERO.server $OMERO -s root@localhost -w omero import /tmp/a.fake 1>&2
echo "::ready:: OMERO.server connection established"
docker-compose logs -f zarr  # Wait for cancellation
