#!/usr/bin/env python

import argparse
import logging

from ome_zarr.io import parse_url
from ome_zarr.reader import Reader


def zarr_checksum_check(filename: str, index: int) -> None:
    loc = parse_url(filename)
    assert loc
    reader = Reader(loc)
    for node in reader():
        if node.data:
            # FIXME: temporary "checksum" to check that some data is present
            assert node.data[index].max().compute() > 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("zarr_uri")
    parser.add_argument("--index", "-i", default=-1, type=int)
    parser.add_argument("--level", "-l", default=30, type=int)
    ns = parser.parse_args()
    logging.basicConfig(level=ns.level)
    zarr_checksum_check(ns.zarr_uri, ns.index)
